version: 2.1
orbs:
  common: jsight/common-ci@1.2.10


parameters:
  go-version:
    type: string
    default: '1.18'
  golangci-lint-version:
    type: string
    default: '1.50.1'

executors:
  docker-nodejs-small:
    docker:
      - image: cimg/node:lts
    resource_class: small

jobs:
  openapi-lint:
    executor: docker-nodejs-small
    steps:
      # - run: 
      #     name: install spectral cli
      #     command: npm install -g @stoplight/spectral-cli
      - checkout
      - run: 
          name: spectral lint
          command: >
            npx @stoplight/spectral-cli lint testdata/jsight_0.3/ser-to-openapi/**/*.openapi -v -D -F

workflows:
  qa:
    jobs:
      - openapi-lint

      - common/go-test: &common-params
          context: online-editor-development
          go-version: << pipeline.parameters.go-version >>

      - common/go-lint:
          <<: *common-params
          golangci-lint-version: << pipeline.parameters.golangci-lint-version >>
          run-mod-vendor: true
